"use client";
import { useRef } from "react";
import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { ArrowRight, CheckCircle2, GitBranch, Search } from "lucide-react";
import { useI18n } from "@/components/providers/locale";
type Requirement = {id:string;name:string;level:number;required:number;gap:number;critical:boolean;assessed:number;closed:boolean};
type Activity = {id:string;title:string;reasons:string[];gains:{skillId:string;gain:number}[]};
export function DevelopmentFlow({current,target,gaps,assessmentDate,recordedSkills,approvedDates,base,activities,history}: {current:{role:string;grade:string};target:{role:string;grade:string};gaps:Requirement[];assessmentDate:string;recordedSkills:string[];approvedDates:Record<string,string>;base:string;activities:Activity[];history:{id:string;title:string;date:string;skills:string[]}[]}) {
  const {t,formatNumber,formatDate}=useI18n();
  const pathname = usePathname();
  const params = useSearchParams();
  const query = params.get("mapQuery") ?? "";
  const filter = params.get("mapFilter") ?? "all";
  const detailsOpen = params.get("mapDetails") === "open";
  function updateMap(changes: Record<string, string | null>) {
    const url = new URL(window.location.href);
    for (const [key, value] of Object.entries(changes)) {
      if (value) url.searchParams.set(key, value); else url.searchParams.delete(key);
    }
    // Next synchronizes native history with useSearchParams without a server fetch per keystroke.
    window.history.replaceState(null, "", url.pathname + url.search + url.hash);
  }
  const inspector=useRef<HTMLDivElement>(null);
  const origin=useRef<HTMLElement|null>(null);
  function closeDetails(){updateMap({mapDetails:null});origin.current?.focus();}
  const groups=[{id:"critical",title:"Critical gaps",skills:gaps.filter(g=>g.critical&&!g.closed),color:"amber"},{id:"develop",title:"Skills to develop",skills:gaps.filter(g=>!g.critical&&!g.closed&&g.level<g.required),color:"blue"},{id:"evidence",title:"Reassessment needed",skills:gaps.filter(g=>!g.critical&&!g.closed&&g.level>=g.required),color:"violet"},{id:"closed",title:"Closed modules",skills:gaps.filter(g=>g.closed),color:"green"}];
  const hr=base.startsWith("/hr/");
  const visible=gaps.filter(g=>(filter==="all"||filter==="open"&&!g.closed||filter==="critical"&&g.critical&&!g.closed||filter==="evidence"&&!g.closed&&g.level>=g.required)&&t(g.name).toLowerCase().includes(query.toLowerCase()));
  const skill = visible.find(g => g.id === params.get("mapSkill")) ?? visible[0];
  const selected = skill?.id;
  const matching=activities.filter(a=>a.gains.some(g=>g.skillId===selected));
  const eligible=matching.filter(a=>!a.reasons.length&&a.gains.some(g=>g.skillId===selected&&g.gain>0));
  const returnTo = `${pathname}?${params.toString()}#trajectory`;
  function choose(id:string){origin.current=document.activeElement as HTMLElement;updateMap({mapSkill:id,mapDetails:"open"});requestAnimationFrame(()=>{inspector.current?.focus({preventScroll:true});});}
  return <section id="trajectory" className="interactive-map">
    <header className="map-heading"><div><p className="eyebrow">{t("EXPLORE YOUR PATH")}</p><h2><GitBranch size={22}/>{t("Development map")}</h2><p>{t("Select a skill to see its evidence and choose your next action.")}</p></div><span className="status-pill">{formatNumber(gaps.filter(g=>g.closed).length)} / {formatNumber(gaps.length)} {t("Closed modules")}</span></header>
    <div className="map-toolbar"><label><Search size={16}/><span className="sr-only">{t("Search skills")}</span><input value={query} onChange={e=>updateMap({mapQuery:e.target.value,mapSkill:null,mapDetails:null})} placeholder={t("Search skills")}/></label><div role="group" aria-label={t("Filter skills")}>{[["all","All"],["open","Open"],["critical","Critical"],["evidence","Reassessment needed"]].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>updateMap({mapFilter:id,mapSkill:null,mapDetails:null})}>{t(label)}</button>)}</div></div>
    <div className="flowchart-workspace"><div className="flowchart-scroll" aria-label={t("Development flowchart")}><div className="flowchart-canvas"><div className="flowchart-profile"><small>{t("Current profile")}</small><strong>{t(current.grade)} · {t(current.role)}</strong><span>{t("Your existing skill evidence")}</span></div><div className="flowchart-trunk" aria-hidden="true"/><div className="map-branches flowchart-branches">{groups.map(group=>{const items=group.skills.filter(g=>visible.some(v=>v.id===g.id));return items.length?<section key={group.id} className={`map-branch flowchart-branch map-${group.color}`}><h3>{t(group.title)} <span>{items.length}</span></h3><div>{items.map(g=><button key={g.id} type="button" className="map-node" aria-pressed={selected===g.id} aria-controls="map-inspector" onClick={()=>choose(g.id)}><span className="flex items-center justify-between gap-2"><strong>{t(g.name)}</strong>{g.closed?<CheckCircle2 size={16}/>:<ArrowRight size={15}/>}</span><span className="map-node-meta">{t("Effective level")}: {formatNumber(g.level,0)} / {formatNumber(g.required)}{!g.closed&&g.level>=g.required&&<em>{t("Evidence needed")}</em>}</span><span className="mt-2 block text-[10px] text-slate-500">{t("Assessment baseline")}: {recordedSkills.includes(g.id)?formatNumber(g.assessed,0):"—"} / {formatNumber(g.required)}</span><progress value={g.assessed} max={g.required||1} aria-label={`${t(g.name)} · ${t("Assessment baseline")}`} /></button>)}</div></section>:null;})}{!visible.length&&<p className="p-6 text-sm text-muted-foreground">{t("No skills match your filters.")}</p>}</div><div className="flowchart-trunk" aria-hidden="true"/><Link className="flowchart-profile flowchart-target" href={`${base}?view=plan`}><small>{t("Career goal")}</small><strong>{t(target.grade)} · {t(target.role)}</strong><span>{t("Edit direction")} →</span></Link><p className="map-footnote mt-5 text-center">{t("Branches group requirements, not task order. Bars show assessment evidence; learning gains do not close modules.")}</p></div></div>
    {detailsOpen && skill && <button className="flowchart-backdrop" aria-label={t("Close skill details")} onClick={closeDetails}/>}<div ref={inspector} tabIndex={-1} id="map-inspector" className={`map-inspector flowchart-inspector ${detailsOpen && skill?"flowchart-inspector-open":""}`} onKeyDown={e=>{if(e.key==="Escape")closeDetails(); if(e.key==="Tab" && window.innerWidth<1280){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('a[href],button,summary')); const first=items[0],last=items.at(-1); if(e.shiftKey&&(document.activeElement===first||document.activeElement===e.currentTarget)){e.preventDefault();last?.focus();} else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} aria-label={t("Selected skill details")}>{skill&&<><button className="flowchart-close" onClick={closeDetails}>{t("Back to map")} ×</button><p className="eyebrow">{t(skill.closed?"Already demonstrated":skill.level>=skill.required?"Evidence needed":"YOUR NEXT OPPORTUNITY")}</p><h3>{t(skill.name)}</h3><div className="map-levels"><div><small>{t("Assessment baseline")}</small><strong>{recordedSkills.includes(skill.id)?formatNumber(skill.assessed,0):"—"}</strong></div><div><small>{t("Effective level")}</small><strong>{formatNumber(skill.level,0)}</strong></div><div><small>{t("Required")}</small><strong>{formatNumber(skill.required)}</strong></div></div><p className="map-explanation">{t(skill.closed?"Supported by assessment baseline":skill.level>=skill.required?"Learning has reached the target level. Assessment evidence is still needed to close this module.":"Build this skill through relevant activity, then demonstrate it with evidence.")}</p><p className="text-xs text-muted-foreground">{recordedSkills.includes(skill.id)?`${t(approvedDates[skill.id] ? "Latest approved review:" : "Imported assessment")} · ${formatDate(approvedDates[skill.id] ?? assessmentDate)}`:t("No assessment recorded; calculations use zero")}</p>
    {!skill.closed&&skill.level>=skill.required&&<Link className="journey-button" href={hr?`${base}?view=reviews`:"/employee/reviews"}>{t("Prepare your review")}<ArrowRight size={15}/></Link>}
    <h4 className="mt-6 text-sm font-semibold">{t("Activities you can explore")}</h4>{eligible.length?eligible.map(a=><Link className="map-activity" key={a.id} href={hr?`${base}?view=advisor`:`/employee/learning?event=${encodeURIComponent(a.id)}&returnTo=${encodeURIComponent(returnTo)}`}><strong>{t(a.title)}</strong><span>{t(hr?"Discuss with advisor":"Explore and add to plan")} <ArrowRight size={14}/></span></Link>):<div className="mt-3 text-sm text-muted-foreground"><p>{t("No eligible activity offers an additional gain for this skill.")}</p><Link className="mt-3 inline-block font-semibold underline" href={`${base}?view=plan`}>{t("Plan an action or collect evidence")} →</Link></div>}
    <details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">{t("Completed learning")} ({history.filter(h=>h.skills.includes(skill.id)).length})</summary><p className="mt-2 text-xs text-muted-foreground">{t("Participation records are not assessments. Historical completions may already be included in the baseline.")}</p>{history.filter(h=>h.skills.includes(skill.id)).map(h=><p key={h.id} className="mt-3 text-xs">{t(h.title)} · {formatDate(h.date)}</p>)}</details>
    {!!matching.filter(a=>!eligible.includes(a)).length&&<details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">{t("Other matching activities")}</summary>{matching.filter(a=>!eligible.includes(a)).map(a=><div className="mt-3 text-xs" key={a.id}><strong>{t(a.title)}</strong><p className="mt-1 text-muted-foreground">{a.reasons.length?a.reasons.map(r=>t(r)).join(" · "):t("No additional gain")}</p></div>)}</details>}
    </>}</div></div></section>;
}
