import type { Locale } from "../i18n";

const copy = {
  relatedHistory: ["Participation in this activity and activities developing the same skills", "Участие в этой активности и активностях, развивающих те же навыки", "Осы іс-шараға және сол дағдыларды дамытатын іс-шараларға қатысу"],
  alternative: ["Eligible alternative", "Доступная альтернатива", "Қолжетімді балама"],
  criticalGains: ["Critical target gaps improved", "Сокращаемые критические дефициты для цели", "Мақсат үшін қысқаратын маңызды дағды олқылықтары"],
  selectedStep: ["selected step", "выбранный шаг", "таңдалған қадам"],
  closesGaps: ["This step develops skills below your target requirements.", "Этот шаг развивает навыки ниже требований вашей цели.", "Бұл қадам мақсатыңыздың талаптарына жетпейтін дағдыларды дамытады."],
  chatGrounded: ["Connected to your development context", "На основе контекста развития", "Даму контекстіне негізделген"],
  chatContext: ["Context & preferences", "Контекст и предпочтения", "Контекст және қалаулар"],
  closeContext: ["Close context", "Закрыть контекст", "Контексті жабу"],
  chatConversation: ["Conversation with your advisor", "Диалог с помощником", "Кеңесшімен диалог"],
  chatLoading: ["Loading your conversation…", "Загружаем диалог…", "Диалог жүктелуде…"],
  chatWelcome: ["What’s your next chapter?", "Какой будет ваш следующий шаг?", "Келесі қадамыңыз қандай?"],
  chatNext: ["Find my next development step", "Выбрать следующий шаг развития", "Келесі даму қадамын таңдау"],
  chatGaps: ["Understand my critical skill gaps", "Разобрать ключевые дефициты навыков", "Маңызды дағды олқылықтарын түсіну"],
  chatGoal: ["Help me shape a career goal", "Помочь сформулировать карьерную цель", "Мансаптық мақсат құруға көмектесу"],
  gapStarter: ["Explain my critical target skill gaps using the recorded evidence. What should I clarify?", "Объясни ключевые дефициты навыков для моей цели по записанным данным. Что нужно уточнить?", "Тіркелген деректер бойынша мақсатым үшін маңызды дағды олқылықтарын түсіндір. Нені нақтылау керек?"],
  goalStarter: ["Help me formulate my career goal. Ask me what you need to know before proposing one.", "Помоги сформулировать карьерную цель. Сначала задай необходимые вопросы.", "Мансаптық мақсатымды тұжырымдауға көмектес. Алдымен қажетті сұрақтарды қой."],
  chatYou: ["You", "Вы", "Сіз"],
  chatAdvisor: ["Career advisor", "Карьерный помощник", "Мансап кеңесшісі"],
  chatCopy: ["Copy answer", "Скопировать ответ", "Жауапты көшіру"],
  chatCopied: ["Copied", "Скопировано", "Көшірілді"],
  copyFailed: ["Could not copy this answer.", "Не удалось скопировать ответ.", "Жауап көшірілмеді."],
  checking: ["Checking your saved context…", "Проверяем сохранённый контекст…", "Сақталған контекст тексерілуде…"],
  thinking: ["Preparing an evidence-based answer…", "Готовим ответ на основе данных…", "Деректерге негізделген жауап дайындалуда…"],
  validating: ["Verifying sources and recommendations…", "Проверяем источники и рекомендации…", "Дереккөздер мен ұсыныстар тексерілуде…"],
  chatInterrupted: ["The response was interrupted. You can retry your message.", "Ответ прерван. Можно повторить сообщение.", "Жауап үзілді. Хабарламаны қайталауға болады."],
  stopped: ["Stopped. Your message is available to edit or retry.", "Остановлено. Сообщение можно изменить или повторить.", "Тоқтатылды. Хабарламаны өңдеуге немесе қайталауға болады."],
  chatLatest: ["Latest messages", "Последние сообщения", "Соңғы хабарламалар"],
  chatPreferences: ["Set learning preferences before recommendations", "Уточните предпочтения перед рекомендациями", "Ұсыныстар алдында оқу қалауларын нақтылаңыз"],
  chatTryAgain: ["Try again", "Повторить", "Қайталау"],
  chatStop: ["Stop response", "Остановить ответ", "Жауапты тоқтату"],
  chatHint: ["Enter to send · Shift+Enter for a new line · Question and relevant context sent to OpenAI", "Enter — отправить · Shift+Enter — новая строка · Вопрос и контекст передаются в OpenAI", "Enter — жіберу · Shift+Enter — жаңа жол · Сұрақ пен контекст OpenAI-ға жіберіледі"],
  widgetOpen: ["Ask your advisor", "Спросить помощника", "Кеңесшіден сұрау"],
  widgetClose: ["Minimize chat", "Свернуть чат", "Чатты кішірейту"],
  widgetFull: ["Open full chat", "Открыть полный чат", "Толық чатты ашу"],
  widgetSubject: ["Employee to discuss", "Сотрудник для обсуждения", "Талқыланатын қызметкер"],
  widgetChoose: ["Choose an employee to start a private discussion.", "Выберите сотрудника для отдельного диалога.", "Жеке диалог бастау үшін қызметкерді таңдаңыз."],
  constraintsTitle: ["Before recommending", "Перед рекомендацией", "Ұсыныс бермес бұрын"],
  constraintsQuestion: ["What total duration and formats work for you? Confirm the choices below, including if you have no restrictions.", "Какая общая длительность и форматы вам подходят? Подтвердите параметры ниже, даже если ограничений нет.", "Қандай жалпы ұзақтық пен форматтар қолайлы? Шектеулер болмаса да, төмендегі таңдауды растаңыз."],
  maxHours: ["Maximum hours per activity", "Максимум часов на активность", "Бір іс-шараға ең көп сағат"],
  unlimited: ["No duration limit", "Без ограничения длительности", "Ұзақтық шектеуі жоқ"],
  formats: ["Acceptable formats", "Подходящие форматы", "Қолайлы форматтар"],
  anyFormat: ["Any format", "Любой формат", "Кез келген формат"],
  constraintsHint: ["This is total catalog duration, not hours per week. Leave duration blank and formats unchecked for no restrictions.", "Это общая длительность по каталогу, а не часы в неделю. Пустая длительность и невыбранные форматы означают отсутствие ограничений.", "Бұл апталық уақыт емес, каталогтағы жалпы ұзақтық. Шектеу болмаса, ұзақтықты бос қалдырып, форматтарды таңдамаңыз."],
  notes: ["Other context (self-reported)", "Другой контекст (с ваших слов)", "Қосымша контекст (өз мәлімдемеңіз)"],
  notesHint: ["Optional: circumstances the assistant should clarify. Notes are not a verified assessment or an automatic filter.", "Необязательно: обстоятельства для уточнения помощником. Текст не является подтверждённой оценкой или автоматическим фильтром.", "Міндетті емес: көмекші нақтылайтын жағдайлар. Мәтін расталған баға немесе автоматты сүзгі емес."],
  confirmConstraints: ["Confirm these choices", "Подтвердить параметры", "Таңдауды растау"],
  confirmedConstraints: ["Choices saved. You can edit them before asking again.", "Параметры сохранены. Их можно изменить перед новым вопросом.", "Таңдау сақталды. Қайта сұрамас бұрын өзгерте аласыз."],
  consultationDuration: ["Exceeds your confirmed duration limit", "Превышает подтверждённый лимит времени", "Расталған уақыт шектеуінен асады"],
  consultationFormat: ["Outside your confirmed formats", "Не соответствует подтверждённым форматам", "Расталған форматтарға сәйкес емес"],
  blockedCatalog: ["No eligible activity improves this target within your confirmed choices. Review the constraints or discuss another development step; no match will be invented.", "Нет подходящей активности, улучшающей навыки цели в рамках ваших параметров. Пересмотрите ограничения или обсудите другой шаг развития; совпадение не будет придумано.", "Расталған таңдауға сай мақсат дағдыларын жақсартатын іс-шара жоқ. Шектеулерді қайта қараңыз немесе басқа даму қадамын талқылаңыз; сәйкестік ойдан шығарылмайды."],
  blockedUnmapped: ["This goal has no catalog role mapping. You can clarify an outcome or edit the plan; catalog recommendations are withheld.", "Цель не связана с ролью каталога. Можно уточнить результат или изменить план; рекомендации активностей пока недоступны.", "Мақсат каталог рөлімен байланыспаған. Нәтижені нақтылауға немесе жоспарды өзгертуге болады; іс-шара ұсыныстары әзірге берілмейді."],
  title: ["Development assistant", "Помощник по развитию", "Даму көмекшісі"],
  activityTitle: ["Activity advisor", "Помощник по активностям", "Іс-шаралар кеңесшісі"],
  hrTitle: ["Prepare a development discussion", "Подготовить разговор о развитии", "Даму туралы әңгімеге дайындық"],
  description: ["Ask about your goal, skill gaps or next step. Answers use this profile, saved plan and catalog.", "Спросите о цели, дефицитах навыков или следующем шаге. Ответы опираются на этот профиль, сохранённый план и каталог.", "Мақсат, дағды олқылықтары немесе келесі қадам туралы сұраңыз. Жауаптар осы профильге, сақталған жоспарға және каталогқа сүйенеді."],
  privacy: ["Your question and relevant evidence are sent to OpenAI. Advice is stored for this demo; it does not change skills or enroll you.", "Вопрос и относящиеся к нему данные отправляются в OpenAI. Совет сохраняется в демо; он не меняет навыки и не записывает на обучение.", "Сұрақ пен тиісті деректер OpenAI-ға жіберіледі. Кеңес демода сақталады; ол дағдыларды өзгертпейді және оқуға тіркемейді."],
  placeholder: ["What would you like help with?", "С чем нужна помощь?", "Қандай көмек керек?"],
  send: ["Ask assistant", "Спросить помощника", "Көмекшіден сұрау"],
  working: ["Checking your evidence…", "Проверяем данные…", "Деректер тексерілуде…"],
  starter: ["Help me choose my next development step. Ask if important context is missing.", "Помоги выбрать следующий шаг развития. Уточни, если не хватает важных данных.", "Дамудың келесі қадамын таңдауға көмектес. Маңызды деректер жетіспесе, нақтыла."],
  activityStarter: ["Explain how this activity fits my saved goal, its prerequisites and a useful alternative.", "Объясни связь этой активности с моей сохранённой целью, требования к участию и подходящую альтернативу.", "Бұл іс-шараның сақталған мақсатыма сәйкестігін, қатысу талаптарын және пайдалы баламаны түсіндір."],
  hrStarter: ["Prepare a development discussion brief for this employee using the saved goal, gaps and participation evidence. Identify what to clarify.", "Подготовь разговор о развитии сотрудника по сохранённой цели, дефицитам навыков и истории участия. Укажи, что уточнить.", "Қызметкердің сақталған мақсаты, дағды олқылықтары және қатысу деректері бойынша даму туралы әңгіме дайында. Нені нақтылау керегін көрсет."],
  start: ["Help me get started", "Помоги начать", "Бастауға көмектес"],
  sources: ["Evidence used", "Использованные данные", "Пайдаланылған деректер"],
  source: ["Source", "Источник", "Дереккөз"],
  profile: ["Profile", "Профиль", "Профиль"],
  policy: ["Calculation rules", "Правила расчёта", "Есептеу ережелері"],
  participation: ["Participation summary", "Сводка участия", "Қатысу қорытындысы"],
  statement: ["Attributed chat statement", "Заявление в диалоге", "Диалогтағы мәлімдеме"],
  interpretation: ["AI-assisted · facts from system records", "С помощью ИИ · факты из записей системы", "ЖИ көмегімен · фактілер жүйе жазбаларынан"],
  goalIntro: ["First, choose a goal in your own words. A suggested goal takes effect only when you accept it.", "Сначала определите цель своими словами. Предложенная цель начнёт действовать только после вашего принятия.", "Алдымен мақсатты өз сөзіңізбен анықтаңыз. Ұсынылған мақсат сіз қабылдағаннан кейін ғана сақталады."],
  factsIntro: ["These recorded facts connect your saved goal with the available development options.", "Эти факты связывают сохранённую цель с доступными вариантами развития.", "Бұл тіркелген фактілер сақталған мақсатты қолжетімді даму нұсқаларымен байланыстырады."],
  hrIntro: ["Use these recorded facts and questions for a development discussion. Target gaps are not current-role performance ratings.", "Используйте эти факты и вопросы для разговора о развитии. Разрывы с целевым грейдом не являются оценкой работы в текущей должности.", "Даму туралы әңгімеде осы фактілер мен сұрақтарды пайдаланыңыз. Мақсатты грейдке қатысты олқылықтар қазіргі жұмыстың бағасы емес."],
  missingAssessment: ["No assessment recorded; calculations use zero", "Оценка не записана; в расчётах используется ноль", "Баға тіркелмеген; есептеуде нөл қолданылады"],
  historyLimit: ["Participation does not establish competence or the reason for an absence.", "Участие не доказывает компетентность или причину пропуска.", "Қатысу құзыреттілікті немесе келмеу себебін дәлелдемейді."],
  selfReport: ["Attributed statement, not a verified assessment.", "Заявление автора, а не подтверждённая оценка.", "Автордың мәлімдемесі, расталған баға емес."],
  prospective: ["If completed, the catalog rule projects", "При выполнении правило каталога даёт расчётный прирост", "Аяқталса, каталог ережесі бойынша болжанатын өсім"],
  targetPolicy: ["Included through the prototype target-role policy; actual enrollment needs employer confirmation.", "Доступно по правилу целевой роли в прототипе; реальное участие требует подтверждения работодателя.", "Прототиптің мақсатты рөл ережесі бойынша қосылған; нақты қатысу жұмыс берушінің растауын қажет етеді."],
  assessmentLimit: ["Activity gains do not approve a skill rating or close an assessment module.", "Прирост от активности не утверждает оценку навыка и не закрывает модуль оценки.", "Іс-шара өсімі дағды бағасын бекітпейді және бағалау модулін жаппайды."],
  rules: ["Rules fallback · no AI advice generated", "Резервный режим · совет ИИ не сформирован", "Ережелер бойынша жауап · ЖИ кеңесі жасалмады"],
  needs_goal: ["Goal clarification", "Уточнение цели", "Мақсатты нақтылау"],
  needs_input: ["Waiting for your answer", "Ожидаем ваш ответ", "Жауабыңыз күтілуде"],
  ready: ["Evidence-backed options", "Варианты на основе данных", "Деректерге негізделген нұсқалар"],
  no_match: ["No supported activity selected", "Подтверждённая активность не выбрана", "Негізделген іс-шара таңдалмады"],
  explained: ["Evidence explained", "Данные объяснены", "Деректер түсіндірілді"],
  hrAvailable: ["Open an employee profile to prepare an AI-assisted development discussion using their saved goal and evidence.", "Откройте профиль сотрудника, чтобы с помощью ИИ подготовить разговор о развитии по сохранённой цели и данным.", "Сақталған мақсат пен деректерге сүйеніп, ЖИ көмегімен даму туралы әңгіме дайындау үшін қызметкер профилін ашыңыз."],
  goalQuestion: ["What would you like to achieve or change? A role or grade is optional.", "Чего вы хотите достичь или что изменить? Должность и грейд необязательны.", "Неге қол жеткізгіңіз келеді немесе нені өзгерткіңіз келеді? Лауазым мен грейд міндетті емес."],
  fallback: ["AI assistance is temporarily unavailable. Your saved facts and plan remain available; no recommendation or assessment was invented. Retry or edit your plan below.", "Помощь ИИ временно недоступна. Сохранённые факты и план доступны; рекомендация или оценка не придуманы. Повторите запрос или измените план.", "ЖИ көмегі уақытша қолжетімсіз. Сақталған фактілер мен жоспар қолжетімді; ұсыныс не баға ойдан шығарылған жоқ. Қайталап көріңіз немесе жоспарды өңдеңіз."],
  not_configured: ["AI is not configured on this server.", "ИИ не настроен на сервере.", "Серверде ЖИ бапталмаған."],
  authentication: ["OpenAI rejected the server credentials. The maintainer needs to update the API key.", "OpenAI отклонил учётные данные сервера. Администратору нужно обновить API-ключ.", "OpenAI сервердің тіркелгі деректерін қабылдамады. Әкімші API кілтін жаңартуы керек."],
  timeout: ["The response deadline was reached.", "Время ожидания ответа истекло.", "Жауапты күту уақыты аяқталды."],
  unavailable: ["The AI service could not complete the request.", "Сервис ИИ не смог выполнить запрос.", "ЖИ қызметі сұрауды орындай алмады."],
  invalid_output: ["The generated response failed evidence validation.", "Ответ не прошёл проверку данных.", "Жасалған жауап деректерді тексеруден өтпеді."],
  error: ["Could not load assistance. Please retry.", "Не удалось получить помощь. Повторите запрос.", "Көмекті жүктеу мүмкін болмады. Қайталап көріңіз."],
  stale: ["Your plan, consultation or dataset changed. Reload this page before asking again.", "План, параметры консультации или данные изменились. Обновите страницу перед новым запросом.", "Жоспар, кеңес параметрлері немесе деректер өзгерді. Қайта сұрамас бұрын бетті жаңартыңыз."],
  limited: ["Please wait before sending another request.", "Подождите перед следующим запросом.", "Келесі сұрауды жібермес бұрын күтіңіз."],
  choose: ["Activity to discuss", "Активность для обсуждения", "Талқылайтын іс-шара"],
  draft: ["Proposed goal · not saved", "Предложенная цель · не сохранена", "Ұсынылған мақсат · сақталмаған"],
  accept: ["Use as my focus goal", "Сделать моей основной целью", "Негізгі мақсатым ету"],
  saved: ["Goal saved. Ask again to use the updated plan.", "Цель сохранена. Задайте новый вопрос по обновлённому плану.", "Мақсат сақталды. Жаңартылған жоспар бойынша қайта сұраңыз."],
  plan: ["Open saved plan", "Открыть сохранённый план", "Сақталған жоспарды ашу"],
  history: ["Saved conversation", "Сохранённый диалог", "Сақталған диалог"],
  retry: ["Reload assistant", "Обновить помощника", "Көмекшіні қайта жүктеу"],
} as const;
export type CopyKey = keyof typeof copy;
export function aiText(locale: Locale, key: CopyKey) { return copy[key][locale === "ru" ? 1 : locale === "kk" ? 2 : 0]; }
