import type { Locale } from "../i18n";
const copy = {
  decisionTitle: ["Review decision", "Решение по оценке", "Бағалау шешімі"],
  decisionHelp: ["HR or the current line manager can approve or return this submission. Approval updates only the reviewed skills; promotion is a separate decision.", "HR или текущий руководитель может утвердить либо вернуть самооценку. Утверждение обновляет только рассмотренные навыки; повышение — отдельное решение.", "HR немесе қазіргі жетекші бағалауды бекіте алады не қайтара алады. Тек қаралған дағдылар жаңартылады; жоғарылату — бөлек шешім."],
  calibrationMissing: ["AI calibration has not run. This is a human-only decision based on the submitted evidence.", "Калибровка ИИ не выполнена. Это решение человека на основе отправленных данных.", "ЖИ калибрлеуі орындалмаған. Бұл жіберілген деректерге сүйенген адамның шешімі."],
  finalRating: ["Final rating", "Итоговая оценка", "Қорытынды баға"],
  baseline: ["Assessment at submission", "Оценка на момент отправки", "Жіберілген сәттегі баға"],
  comment: ["Decision comment (required)", "Комментарий к решению (обязательно)", "Шешім түсіндірмесі (міндетті)"],
  approve: ["Approve review", "Утвердить оценку", "Бағалауды бекіту"],
  return: ["Return for clarification", "Вернуть на уточнение", "Нақтылауға қайтару"],
  approved: ["Approved", "Утверждено", "Бекітілді"],
  returned: ["Returned for clarification", "Возвращено на уточнение", "Нақтылауға қайтарылды"],
  decisionRequired: ["Choose a final rating for every skill and add a comment to approve. A return requires a comment only.", "Для утверждения выберите итоговую оценку по каждому навыку и добавьте комментарий. Для возврата достаточно комментария.", "Бекіту үшін әр дағдыға қорытынды баға қойып, түсіндірме жазыңыз. Қайтару үшін түсіндірме жеткілікті."],
  assessmentChanged: ["An assessment changed after submission. Return this review and ask the employee to reopen and resubmit it with current evidence.", "После отправки оценка изменилась. Верните эту версию и попросите сотрудника открыть и отправить новую с актуальными данными.", "Жіберілгеннен кейін баға өзгерді. Осы нұсқаны қайтарып, қызметкерден өзекті деректермен қайта жіберуін сұраңыз."],
  hrActor: ["HR demo account", "Демо-аккаунт HR", "HR демо тіркелгісі"],
  submittedEvidence: ["Submitted self-assessment", "Отправленная самооценка", "Жіберілген өзіндік баға"],

  title: ["Quarterly reviews", "Квартальная оценка", "Тоқсандық бағалау"],
  description: ["Explain what you did and the business result for each target skill. Submission preserves your original assessment for a human decision. AI calibration is not yet available.", "По каждому целевому навыку опишите, что вы сделали и какой результат получили. Отправка сохраняет исходную самооценку для решения человека. Калибровка ИИ пока недоступна.", "Әр мақсатты дағды бойынша не істегеніңізді және нәтижесін сипаттаңыз. Жіберу бастапқы өзіндік бағаны адамның шешімі үшін сақтайды. ЖИ калибрлеуі әзірге қолжетімсіз."],
  own: ["My reviews", "Мои оценки", "Менің бағалауым"],
  reports: ["Direct reports", "Прямые подчинённые", "Тікелей бағыныстылар"],
  quarter: ["Completed quarter (YYYY-QN)", "Завершённый квартал (YYYY-QN)", "Аяқталған тоқсан (YYYY-QN)"],
  create: ["Open review", "Открыть оценку", "Бағалауды ашу"],
  draft: ["Draft", "Черновик", "Жоба"],
  submitted: ["Submitted · awaiting human review", "Отправлено · ожидает рассмотрения", "Жіберілді · қарауды күтуде"],
  rating: ["Self-rating (0–5)", "Самооценка (0–5)", "Өзіндік баға (0–5)"],
  justification: ["Business justification: action and result", "Обоснование: действие и результат", "Негіздеме: әрекет және нәтиже"],
  missing: ["Every skill needs a rating and a nonblank justification before submission.", "Для отправки нужны оценка и непустое обоснование по каждому навыку.", "Жіберу үшін әр дағдыға баға және бос емес негіздеме қажет."],
  save: ["Save draft", "Сохранить черновик", "Жобаны сақтау"],
  submit: ["Submit assessment", "Отправить самооценку", "Өзіндік бағаны жіберу"],
  reopen: ["Create editable revision", "Создать редактируемую версию", "Өңделетін нұсқа жасау"],
  history: ["Revision history and frozen evidence", "История версий и зафиксированные данные", "Нұсқалар тарихы және бекітілген деректер"],
  noManager: ["No line manager assigned. HR can review this submission.", "Руководитель не назначен. HR может рассмотреть самооценку.", "Жетекші тағайындалмаған. Өзіндік бағаны HR қарай алады."],
  manager: ["Reviewer at this revision", "Проверяющий в этой версии", "Осы нұсқадағы тексеруші"],
  readonly: ["Self-assessments stay unchanged. HR and current line managers can record a separate decision.", "Самооценки не редактируются. HR и текущий руководитель записывают отдельное решение.", "Өзіндік бағалар өзгертілмейді. HR және қазіргі жетекші бөлек шешім тіркей алады."],
  none: ["No review opened yet.", "Оценка ещё не открыта.", "Бағалау әлі ашылмаған."],
  error: ["Could not save. Check the completed quarter, role-linked focus goal and required fields.", "Не удалось сохранить. Проверьте завершённый квартал, связь цели с ролью и обязательные поля.", "Сақталмады. Аяқталған тоқсанды, мақсаттың рөлмен байланысын және міндетті өрістерді тексеріңіз."],
  stale: ["This record or dataset changed. Reload before editing.", "Запись или данные изменились. Обновите перед редактированием.", "Жазба немесе деректер өзгерді. Өңдеуден бұрын жаңартыңыз."],
  reload: ["Reload reviews", "Обновить оценки", "Бағалауды жаңарту"],
  scale: ["Proficiency scale", "Шкала владения", "Меңгеру шкаласы"],
  noScale: ["This stored dataset has no proficiency descriptions; numeric levels are 0–5. Import/reset with a scale before interpreting these levels.", "В сохранённых данных нет описаний уровней; числовая шкала — 0–5. Для интерпретации загрузите данные со шкалой или сбросьте демо.", "Сақталған деректерде деңгей сипаттамалары жоқ; сандық шкала — 0–5. Түсіндіру үшін шкаласы бар деректерді жүктеңіз немесе демоны қалпына келтіріңіз."],
  evidence: ["Evidence captured at submission, not proof of workplace competence. History may extend beyond the named quarter; its dates remain visible.", "Данные зафиксированы при отправке и не доказывают рабочую компетентность. История может выходить за рамки квартала; даты сохранены.", "Деректер жіберілген сәтте бекітіледі, бірақ жұмыс құзыреттілігін дәлелдемейді. Тарих тоқсан шегінен шығуы мүмкін; күндері көрсетіледі."],
} as const;
export function reviewText(locale: Locale, key: keyof typeof copy) { return copy[key][locale === "ru" ? 1 : locale === "kk" ? 2 : 0]; }
