import type { Locale } from "../i18n";
const copy = {
  title: ["Quarterly reviews", "Квартальная оценка", "Тоқсандық бағалау"],
  description: ["Explain what you did and the business result for each target skill. Submission preserves your original assessment; calibration and approval are the next stage.", "По каждому целевому навыку опишите, что вы сделали и какой результат получили. Отправка сохраняет исходную самооценку; калибровка и согласование — следующий этап.", "Әр мақсатты дағды бойынша не істегеніңізді және нәтижесін сипаттаңыз. Жіберу бастапқы өзіндік бағаны сақтайды; калибрлеу мен бекіту — келесі кезең."],
  own: ["My reviews", "Мои оценки", "Менің бағалауым"],
  reports: ["Direct reports", "Прямые подчинённые", "Тікелей бағыныстылар"],
  quarter: ["Completed quarter (YYYY-QN)", "Завершённый квартал (YYYY-QN)", "Аяқталған тоқсан (YYYY-QN)"],
  create: ["Open review", "Открыть оценку", "Бағалауды ашу"],
  draft: ["Draft", "Черновик", "Жоба"],
  submitted: ["Submitted · awaiting calibration", "Отправлено · ожидает калибровки", "Жіберілді · калибрлеуді күтуде"],
  rating: ["Self-rating (0–5)", "Самооценка (0–5)", "Өзіндік баға (0–5)"],
  justification: ["Business justification: action and result", "Обоснование: действие и результат", "Негіздеме: әрекет және нәтиже"],
  missing: ["Every skill needs a rating and a nonblank justification before submission.", "Для отправки нужны оценка и непустое обоснование по каждому навыку.", "Жіберу үшін әр дағдыға баға және бос емес негіздеме қажет."],
  save: ["Save draft", "Сохранить черновик", "Жобаны сақтау"],
  submit: ["Submit assessment", "Отправить самооценку", "Өзіндік бағаны жіберу"],
  reopen: ["Create editable revision", "Создать редактируемую версию", "Өңделетін нұсқа жасау"],
  history: ["Revision history and frozen evidence", "История версий и зафиксированные данные", "Нұсқалар тарихы және бекітілген деректер"],
  noManager: ["No line manager assigned. Reviewer assignment is required before future approval.", "Руководитель не назначен. Для будущего согласования потребуется назначить проверяющего.", "Жетекші тағайындалмаған. Кейін бекіту үшін тексерушіні тағайындау қажет."],
  manager: ["Reviewer at this revision", "Проверяющий в этой версии", "Осы нұсқадағы тексеруші"],
  readonly: ["Read-only review inspection. Current managers see only their direct reports.", "Просмотр без редактирования. Руководитель видит только прямых подчинённых.", "Тек қарауға болады. Жетекші тек тікелей бағыныстыларын көреді."],
  none: ["No review opened yet.", "Оценка ещё не открыта.", "Бағалау әлі ашылмаған."],
  error: ["Could not save. Check the completed quarter, role-linked focus goal and required fields.", "Не удалось сохранить. Проверьте завершённый квартал, связь цели с ролью и обязательные поля.", "Сақталмады. Аяқталған тоқсанды, мақсаттың рөлмен байланысын және міндетті өрістерді тексеріңіз."],
  stale: ["This record or dataset changed. Reload before editing.", "Запись или данные изменились. Обновите перед редактированием.", "Жазба немесе деректер өзгерді. Өңдеуден бұрын жаңартыңыз."],
  reload: ["Reload reviews", "Обновить оценки", "Бағалауды жаңарту"],
  scale: ["Proficiency scale", "Шкала владения", "Меңгеру шкаласы"],
  noScale: ["This stored dataset has no proficiency descriptions; numeric levels are 0–5. Import/reset with a scale before interpreting these levels.", "В сохранённых данных нет описаний уровней; числовая шкала — 0–5. Для интерпретации загрузите данные со шкалой или сбросьте демо.", "Сақталған деректерде деңгей сипаттамалары жоқ; сандық шкала — 0–5. Түсіндіру үшін шкаласы бар деректерді жүктеңіз немесе демоны қалпына келтіріңіз."],
  evidence: ["Evidence captured at submission, not proof of workplace competence. History may extend beyond the named quarter; its dates remain visible.", "Данные зафиксированы при отправке и не доказывают рабочую компетентность. История может выходить за рамки квартала; даты сохранены.", "Деректер жіберілген сәтте бекітіледі, бірақ жұмыс құзыреттілігін дәлелдемейді. Тарих тоқсан шегінен шығуы мүмкін; күндері көрсетіледі."],
} as const;
export function reviewText(locale: Locale, key: keyof typeof copy) { return copy[key][locale === "ru" ? 1 : locale === "kk" ? 2 : 0]; }
